[pytest]
testpaths = tests
pythonpath = .
addopts =
    --cov=models
    --cov=interfaces
    --cov=repositories
    --cov=database
    --cov=utils
    --cov-report=term-missing
    --cov-fail-under=100
